-- Migration
CREATE TYPE "UserRole" AS ENUM ('LISTENER', 'ARTIST', 'ADMIN');
CREATE TYPE "TrackStatus" AS ENUM ('PENDING', 'DEPLOYING', 'ACTIVE', 'FAILED', 'REMOVED');
CREATE TYPE "Genre" AS ENUM ('HIP_HOP', 'ELECTRONIC', 'POP', 'RNB', 'ROCK', 'INDIE', 'TRAP', 'HOUSE', 'OTHER');
CREATE TYPE "TokenType" AS ENUM ('TRACK', 'ARTIST');
CREATE TYPE "TransactionType" AS ENUM ('BUY', 'SELL');
CREATE TYPE "ChartType" AS ENUM ('HOT', 'RISING', 'HOLDERS', 'NEW', 'VOLUME', 'GENRE', 'FOR_YOU', 'REGION');
CREATE TYPE "Region" AS ENUM ('RU', 'CIS', 'WORLD');
CREATE TYPE "RoyaltyStatus" AS ENUM ('PENDING', 'CLAIMED');
CREATE TABLE "users" ("id" TEXT NOT NULL,"telegram_id" TEXT NOT NULL,"username" TEXT,"name" TEXT NOT NULL,"avatar_url" TEXT,"role" "UserRole" NOT NULL DEFAULT 'LISTENER',"referral_code" TEXT NOT NULL,"referred_by_id" TEXT,"is_premium" BOOLEAN NOT NULL DEFAULT false,"premium_until" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "users_telegram_id_key" ON "users"("telegram_id");
CREATE UNIQUE INDEX "users_referral_code_key" ON "users"("referral_code");

CREATE TABLE "artists" ("id" TEXT NOT NULL,"user_id" TEXT NOT NULL,"bio" TEXT,"genres" "Genre"[],"country" TEXT,"social_telegram" TEXT,"social_vk" TEXT,"social_instagram" TEXT,"is_verified" BOOLEAN NOT NULL DEFAULT false,"registration_tx_hash" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "artists_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "artists_user_id_key" ON "artists"("user_id");

CREATE TABLE "tracks" ("id" TEXT NOT NULL,"artist_id" TEXT NOT NULL,"title" TEXT NOT NULL,"genre" "Genre" NOT NULL,"year" INTEGER NOT NULL,"lyrics" TEXT,"audio_url" TEXT NOT NULL,"cover_url" TEXT,"duration_sec" INTEGER NOT NULL,"status" "TrackStatus" NOT NULL DEFAULT 'PENDING',"total_plays" INTEGER NOT NULL DEFAULT 0,"unique_listeners" INTEGER NOT NULL DEFAULT 0,"completion_rate" DOUBLE PRECISION NOT NULL DEFAULT 0,"library_count" INTEGER NOT NULL DEFAULT 0,"like_count" INTEGER NOT NULL DEFAULT 0,"comment_count" INTEGER NOT NULL DEFAULT 0,"share_count" INTEGER NOT NULL DEFAULT 0,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "tracks_pkey" PRIMARY KEY ("id"));

CREATE TABLE "track_tokens" ("id" TEXT NOT NULL,"track_id" TEXT NOT NULL,"contract_address" TEXT NOT NULL,"ticker" TEXT NOT NULL,"total_supply" TEXT NOT NULL DEFAULT '1000000000',"current_price_ton" TEXT NOT NULL DEFAULT '0.000001',"price_change_24h" DOUBLE PRECISION NOT NULL DEFAULT 0,"holder_count" INTEGER NOT NULL DEFAULT 0,"volume_24h" TEXT NOT NULL DEFAULT '0',"market_cap_ton" TEXT NOT NULL DEFAULT '0',"lp_locked" BOOLEAN NOT NULL DEFAULT false,"lp_locked_at" TIMESTAMP(3),"lp_tx_hash" TEXT,"lp_amount" TEXT,"deploy_tx_hash" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "track_tokens_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "track_tokens_track_id_key" ON "track_tokens"("track_id");
CREATE UNIQUE INDEX "track_tokens_contract_address_key" ON "track_tokens"("contract_address");

CREATE TABLE "artist_tokens" ("id" TEXT NOT NULL,"artist_id" TEXT NOT NULL,"contract_address" TEXT NOT NULL,"ticker" TEXT NOT NULL,"total_supply" TEXT NOT NULL DEFAULT '100000000',"current_price_ton" TEXT NOT NULL DEFAULT '0.000001',"price_change_24h" DOUBLE PRECISION NOT NULL DEFAULT 0,"holder_count" INTEGER NOT NULL DEFAULT 0,"volume_24h" TEXT NOT NULL DEFAULT '0',"market_cap_ton" TEXT NOT NULL DEFAULT '0',"lp_locked" BOOLEAN NOT NULL DEFAULT false,"lp_locked_at" TIMESTAMP(3),"lp_tx_hash" TEXT,"royalty_flow_7d" TEXT NOT NULL DEFAULT '0',"deploy_tx_hash" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "artist_tokens_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "artist_tokens_artist_id_key" ON "artist_tokens"("artist_id");
CREATE UNIQUE INDEX "artist_tokens_contract_address_key" ON "artist_tokens"("contract_address");

CREATE TABLE "token_holders" ("id" TEXT NOT NULL,"user_id" TEXT NOT NULL,"token_type" "TokenType" NOT NULL,"track_token_id" TEXT,"artist_token_id" TEXT,"amount" TEXT NOT NULL,"avg_buy_price" TEXT NOT NULL DEFAULT '0',"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "token_holders_pkey" PRIMARY KEY ("id"));

CREATE TABLE "price_history" ("id" TEXT NOT NULL,"track_token_id" TEXT NOT NULL,"price_ton" TEXT NOT NULL,"volume_ton" TEXT NOT NULL DEFAULTcat > prisma/migrations/0001_init/migration_lock.toml << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
